<a href="https://colab.research.google.com/github/delferns2001/FYP/blob/master/10H_Tutorial_Learning_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Creating my First Model**

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(2,input_shape = [1,],activation="relu"))

KeyboardInterrupt: ignored

In [ ]:
model.add(Dense(1))

In [ ]:
model.summary()

In [ ]:
model.compile(optimizer="adam",loss="mse")

In [ ]:
model.fit(x=trainx,y=trainY,epochs=20)

# **Learning and Creating Tensors** **bold text**

In [ ]:
#Importing tensors
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
#Creating tensors with tf.constant()
scalar = tf.constant([1,2,4,5,6,7])
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tf.Tensor([1 2 4 5 6 7], shape=(6,), dtype=int32)
1
(6,)


In [ ]:
#Creating a vector with tf.constant 
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)
print(vector.shape)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1
(2,)


In [ ]:
#Creating a matrix with tf.constant()
matrix = tf.constant([[2,2],
                      [2,2]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)
2
(2, 2)


In [ ]:
#Creating another matrix with tf.constant()
another_matrix = tf.constant([[2,3,4],
                              [2,3,4],
                              [2,4,6]], dtype = tf.int16)

dtype is the level of precision is the level of precision the numbers in the variable are stored

In [ ]:
#lets create a tensor with tf.constant()
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[1,2,3],
                       [4,5,6]]])

print(tensor)
print(tensor.shape)
print(tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
3


In [ ]:
#Creating tensor with tf.variable()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#.assign() lets you change data in a tensor

changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [ ]:
#Creating Tensors with Random data 

#normal means normal distribution
#uniform means uniform distribution 



random_tensor_normal = tf.random.Generator.from_seed(42)
random_tensor_normal = tf.random.normal(shape=(3,4))
print(random_tensor_normal)


random_tensor_uniform = tf.random.Generator.from_seed(42)
random_tensor_uniform = tf.random.normal(shape = (3,4))
print(random_tensor_uniform)



tf.Tensor(
[[ 8.4224582e-02 -8.6090374e-01  3.7812304e-01 -5.1962738e-03]
 [-4.9453196e-01  6.1781919e-01 -3.3082047e-01 -1.3840806e-03]
 [-4.2373410e-01 -1.3872087e+00 -1.5488191e+00 -5.3198391e-01]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-0.55909735 -0.5347214   2.3730333  -1.5725931 ]
 [ 0.8055056  -0.83387697  0.30611223  2.2660494 ]
 [ 0.2856414  -1.5536156   0.37975532  0.76646256]], shape=(3, 4), dtype=float32)


In [ ]:
# Shuffle a tensor (value for when you want to shuffle your data so that the inherent order dosen't effect learning)

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [12,3]])
tf.random.shuffle(not_shuffled)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [12,  3]], dtype=int32)>

In [ ]:
#Questions to answered

#create a tensor (Changeable and unchangeable)

#create a random tensor (normal distribution) && (uniform distribution)

#create a tensor with float 16 as dtype 

#set the seed to 42

#shuffle the tensors 

In [ ]:
#creates a tensor with all ones with a given shape
tf.ones(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#Numpy Arrays can also be turned into tensors

The main difference between NumPy arrays and TensirFlow tensors is that tensors can be run on the a GPU (much faster for numerical computing)

> `A = tf.constant(numpy_A)`

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (2,3,4))

#shape can be rearranged into a different shape
#but when each demension is multiplied they need to add up to the orignal number of values

In [ ]:
rank_4_tensor = tf.zeros([2,3,4,5],tf.float32)

In [ ]:
#Below is a function that prints( 
#datatypes, number of demension, shape 
#elements at 0 axis, elements last axis 
#number of elements in the tensor(with numpy and without))

def DisplayTensorDetails(tensorName: tf.Variable):
  print("The datatype of tensor: ",tensorName.dtype)
  print("The number of demensions of the tensor: ",tensorName.ndim)
  print("The shape of the tensor is: ", tensorName.shape)
  print("The 0-axis of the tensor is: ", tensorName.shape[0])
  print("The last axis of the tensor is: ",tensorName.shape[-1])
  print("The number of elements in the tensor are: ",tf.size(tensorName))
  print("The number of elements in the tensor are: ",tf.size(tensorName).numpy())

In [ ]:
DisplayTensorDetails(rank_4_tensor)

The datatype of tensor:  <dtype: 'float32'>
The number of demensions of the tensor:  4
The shape of the tensor is:  (2, 3, 4, 5)
The 0-axis of the tensor is:  2
The last axis of the tensor is:  5
The number of elements in the tensor are:  tf.Tensor(120, shape=(), dtype=int32)
The number of elements in the tensor are:  120


In [ ]:
#Get the first two elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from index except for the final one

rank_4_tensor[:1,:1,:1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor and reshape it 

rank_2_tensor = tf.Variable([[10,7],
                             [3,4]])


In [ ]:
#Get the last item of each of our rank 2 tensors 

rank_2_tensor[:,-1:].numpy()

array([[7],
       [4]], dtype=int32)

In [ ]:
#Adding a demension to our rank 2 tensor 

rank_3_tensor = rank_2_tensor[...,tf.newaxis]

In [ ]:
#Changing the demension of the tensors, adding a demension in the last elements

tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Changing the demension of the tensors, adding a demension in the first elements

tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

#**Manipulating tensors (tensor operations**



There are two rules our tensors need to fulfil if we are going to matrix multiply them: 

1. The inner demensions must match
2. The resulting matrix has the shape of the outer dimensions 

In [ ]:
# Change values of the tensor using maths operators 
#Addition #Multiplication #Subtraction, Devision 

tensor = tf.constant([[10,7],[3,4]])

tensor + 10,tensor *10,tensor -10,tensor/10


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [ ]:
#Tf.(math operator) 

#Tf.(math operator) are much faster then just -> tensor (operator) 10  
# cause it use GPU capabilities

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Multiplying Matrixes 
# Multiplying Matrixes can be done using dot product 


tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Exerise Multiplying Matrixes 1

tensor1 = tf.Variable([[1,2,5],[7,2,1],[3,3,3]])
tensor2 = tf.Variable([[3,5],[6,7],[1,8]])
tensor1,tensor2

tf.linalg.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X_reshaped = tf.reshape(X,shape=(2,3))
Y_reshaped = tf.reshape(Y,shape=(2,3))




In [ ]:
# Even though same values are use used the resulting vectors are different
# as a result of reshaping each

tf.linalg.matmul(X,Y_reshaped),tf.linalg.matmul(X_reshaped,Y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>)

In [ ]:
#Another way reshape is transpose  

#Reshape 

#Transpose flips the axises 
 
tf.transpose(X),X_reshaped

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.linalg.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
print("Normal Y: ")
print(Y, "\n")


print("Y reshaped to (2,3) ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3) 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally when performing matrix multiplication with two twnsors and one of the axes doesn't line up you will transpose (rather then reshape) one of the tensors to satisfy the matrix multiplication rules

#**Changing the datatypes of you tensor**

In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1, 7])
C.dtype

tf.int32

In [ ]:
#cast allows to change the precision of each number 
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

##Aggregating tensors

aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Getting the absolute value of the tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets fo through the following forms of aggregation 

1. get the minimum 
2. get the maximum 
3. get the mean of the tensor 
4. get the sum of tensor

In [ ]:
np.random.seed(1)
E = tf.constant(np.random.randint(0,100,size = 50))
E = tf.cast(E,dtype=tf.float16)
E

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([37., 12., 72.,  9., 75.,  5., 79., 64., 16.,  1., 76., 71.,  6.,
       25., 50., 20., 18., 84., 11., 28., 29., 14., 50., 68., 87., 87.,
       94., 96., 86., 13.,  9.,  7., 63., 61., 22., 57.,  1.,  0., 60.,
       81.,  8., 88., 13., 47., 72., 30., 71.,  3., 70., 21.],
      dtype=float16)>

In [ ]:
tf.size(E), E.shape, E.dtype, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 tf.float16,
 1)

In [ ]:
#find the minimum of tensor 
print(tf.reduce_min(E).numpy())


0.0


In [ ]:
print(tf.reduce_max(E).numpy())

96.0


In [ ]:
print(tf.reduce_mean(E).numpy())

43.38


In [ ]:
print(tf.reduce_sum(E).numpy())

2168.0


In [ ]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=982.0>

In [ ]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=31.34>

In [ ]:
#std diviation method 

def getDataPolarity(data):
  sum = 0
  for i in range(tf.size(data).numpy()):
    sum = sum + tf.math.square(data[i].numpy() - tf.reduce_mean(data).numpy())

  sdiv = sum/tf.size(data).numpy()

  print("Standerd Diviation: "+ str(tf.math.sqrt(sdiv).numpy()))
  print("Varianec: " + str(sdiv.numpy()))
  print("tensorflow calculated Standerd Diviation: ",tf.math.reduce_std(data))
  print("tensorflow calculated Varianec: ",tf.math.reduce_variance(data))

In [ ]:
getDataPolarity(E)

Standerd Diviation: 31.34
Varianec: 982.0
tensorflow calculated Standerd Diviation:  tf.Tensor(31.34, shape=(), dtype=float16)
tensorflow calculated Varianec:  tf.Tensor(982.0, shape=(), dtype=float16)


###finding the positional minimum and minimum

In [ ]:
#Create a new tensor for finding positional minimum and maximum 
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find the positional maximum 
np.argmax(F)

42

In [ ]:
#find the index of the largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Find the positional minimum 

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Finding the Value at the positional minimum

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###squeezing a tensor(removin all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# sqeeze removes all singl dimension 
#for example from (1,1,1,1,50) -> (50)

G_squeezed = tf.squeeze(G)
G_squeezed, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 50]))

###**ONE** HOT ENCODING

In [ ]:
#encoding words to numbers
some_list = [0,1,2,3,4,6]

tf.one_hot(some_list, 5)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding

tf.one_hot(some_list, depth=7, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(6, 7), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF', b'OFF', b'OFF', b'ON']],
      dtype=object)>

###Squaring, log, square root

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square rooting requires the user to use floats rather then int, else it will print an error

tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#**Tensors and Numpy**

In [ ]:
#Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different 
# They use different level of accurecy to store data
# They can customed to have the same dtatypes 

numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)